image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_TLS_CERTDIR: ""

stages:
  - deploy

before_script:
  - docker info

deploy:
  stage: deploy
  script:
    - docker compose down
    - docker compose pull || true  # подтянуть образы, если используются из реестра
    - docker compose up -d --build --remove-orphans
    - docker system prune -f  # очистка ненужных образов и контейнеров, опционально
  only:
    - main